"""mouvement stock: montant de vente et encaissement

Revision ID: 0ba331ab0010
Revises: 4a093bd00b5a
Create Date: 2026-08-29 15:22:32.299056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ba331ab0010'
down_revision: Union[str, Sequence[str], None] = '4a093bd00b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mouvements_stock', sa.Column('montant_vente', sa.Numeric(precision=18, scale=2), nullable=True, comment='Prix de vente HT sur une sortie vente'))
    op.add_column('mouvements_stock', sa.Column('montant_encaisse', sa.Numeric(precision=18, scale=2), nullable=True, comment='Ce que le client a effectivement paye'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mouvements_stock', 'montant_encaisse')
    op.drop_column('mouvements_stock', 'montant_vente')
    # ### end Alembic commands ###
