"""facture: TVA optionnelle, zero par defaut

Revision ID: 0f7b371e10ef
Revises: e0dbf28e627c
Create Date: 2026-08-30 14:05:20.604879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7b371e10ef'
down_revision: Union[str, Sequence[str], None] = 'e0dbf28e627c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lignes_proforma', sa.Column('tva_applicable', sa.Boolean(), nullable=False, comment='Coche a la facture si la TVA doit etre appliquee'))
    op.alter_column('lignes_proforma', 'taux_tva',
               existing_type=sa.NUMERIC(precision=7, scale=4),
               comment='0 par defaut : DML est au SMT et ne facture pas la TVA. Passer a 0.1925 si le regime change.',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lignes_proforma', 'taux_tva',
               existing_type=sa.NUMERIC(precision=7, scale=4),
               comment=None,
               existing_comment='0 par defaut : DML est au SMT et ne facture pas la TVA. Passer a 0.1925 si le regime change.',
               existing_nullable=False)
    op.drop_column('lignes_proforma', 'tva_applicable')
    # ### end Alembic commands ###
