"""tva zero sur factures

Revision ID: 1b64ea87c61a
Revises: f50d8b4d3604
Create Date: 2026-08-30 14:21:27.370181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b64ea87c61a'
down_revision: Union[str, Sequence[str], None] = 'f50d8b4d3604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
