"""lot: collecte, collecteur, mode de detention

Revision ID: 2240f159746d
Revises: ff50aad53044
Create Date: 2026-08-28 09:12:42.968007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2240f159746d'
down_revision: Union[str, Sequence[str], None] = 'ff50aad53044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('collecte_id', sa.Uuid(), nullable=True))
    op.add_column('lots', sa.Column('collecteur_id', sa.Uuid(), nullable=True))
    op.add_column('lots', sa.Column('mode_detention', sa.Enum('PROPRIETE', 'CONSIGNATION_POURCENTAGE', 'MARGE_FIXE_TONNE', name='modedetention', native_enum=False, length=50), nullable=False, server_default='PROPRIETE'))
    op.create_index(op.f('ix_lots_collecte_id'), 'lots', ['collecte_id'], unique=False)
    op.create_index(op.f('ix_lots_collecteur_id'), 'lots', ['collecteur_id'], unique=False)
    op.create_index(op.f('ix_lots_mode_detention'), 'lots', ['mode_detention'], unique=False)
    op.create_foreign_key(op.f('fk_lots_collecteur_id_collecteurs'), 'lots', 'collecteurs', ['collecteur_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_lots_collecte_id_collectes'), 'lots', 'collectes', ['collecte_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_traitements_created_by_id_utilisateurs'), 'traitements', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_traitements_updated_by_id_utilisateurs'), 'traitements', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_traitements_updated_by_id_utilisateurs'), 'traitements', type_='foreignkey')
    op.drop_constraint(op.f('fk_traitements_created_by_id_utilisateurs'), 'traitements', type_='foreignkey')
    op.drop_constraint(op.f('fk_lots_collecte_id_collectes'), 'lots', type_='foreignkey')
    op.drop_constraint(op.f('fk_lots_collecteur_id_collecteurs'), 'lots', type_='foreignkey')
    op.drop_index(op.f('ix_lots_mode_detention'), table_name='lots')
    op.drop_index(op.f('ix_lots_collecteur_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_collecte_id'), table_name='lots')
    op.drop_column('lots', 'mode_detention')
    op.drop_column('lots', 'collecteur_id')
    op.drop_column('lots', 'collecte_id')
    # ### end Alembic commands ###
