"""mouvement stock: montant vente et encaisse

Revision ID: 27f24b3677c7
Revises: 0ba331ab0010
Create Date: 2026-08-29 15:29:22.529764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f24b3677c7'
down_revision: Union[str, Sequence[str], None] = '0ba331ab0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
