"""mouvement stock: observations

Revision ID: 4a093bd00b5a
Revises: 2240f159746d
Create Date: 2026-08-29 14:45:17.565999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a093bd00b5a'
down_revision: Union[str, Sequence[str], None] = '2240f159746d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mouvements_stock', sa.Column('observations', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mouvements_stock', 'observations')
    # ### end Alembic commands ###
