"""utilisateur: blocage apres tentatives echouees

Revision ID: 7b76bd3482cf
Revises: 27f24b3677c7
Create Date: 2026-08-29 16:19:41.894621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b76bd3482cf'
down_revision: Union[str, Sequence[str], None] = '27f24b3677c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
