"""module collecte et consignation

Revision ID: d1e3b3a3492f
Revises: 34c672387d9c
Create Date: 2026-08-26 18:53:15.600564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e3b3a3492f'
down_revision: Union[str, Sequence[str], None] = '34c672387d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones_collecte',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('arrondissement', sa.String(length=120), nullable=True),
    sa.Column('departement', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('jour_marche', sa.String(length=60), nullable=True, comment='Jour(s) de tenue du marche hebdomadaire'),
    sa.Column('distance_douala_km', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('accessible_saison_pluies', sa.Boolean(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('is_actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones_collecte'))
    )
    op.create_index(op.f('ix_zones_collecte_code'), 'zones_collecte', ['code'], unique=True)
    op.create_index(op.f('ix_zones_collecte_created_at'), 'zones_collecte', ['created_at'], unique=False)
    op.create_index(op.f('ix_zones_collecte_departement'), 'zones_collecte', ['departement'], unique=False)
    op.create_index(op.f('ix_zones_collecte_is_actif'), 'zones_collecte', ['is_actif'], unique=False)
    op.create_index(op.f('ix_zones_collecte_is_deleted'), 'zones_collecte', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_zones_collecte_region'), 'zones_collecte', ['region'], unique=False)
    op.create_index(op.f('ix_zones_collecte_village'), 'zones_collecte', ['village'], unique=False)
    op.create_table('collecteurs',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=180), nullable=False),
    sa.Column('type_collecteur', sa.Enum('INDEPENDANT', 'SALARIE', 'COOPERATIVE', 'GROSSISTE_MARCHE', name='typecollecteur', native_enum=False, length=50), nullable=False),
    sa.Column('statut', sa.Enum('ACTIF', 'SUSPENDU', 'INACTIF', 'LISTE_NOIRE', name='statutcollecteur', native_enum=False, length=50), nullable=False),
    sa.Column('telephone', sa.String(length=40), nullable=True),
    sa.Column('telephone_mobile_money', sa.String(length=40), nullable=True),
    sa.Column('piece_identite', sa.String(length=60), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('employe_id', sa.Uuid(), nullable=True),
    sa.Column('zone_principale_id', sa.Uuid(), nullable=True),
    sa.Column('mode_detention_habituel', sa.Enum('PROPRIETE', 'CONSIGNATION_POURCENTAGE', 'MARGE_FIXE_TONNE', name='modedetention', native_enum=False, length=50), nullable=False),
    sa.Column('marge_fixe_tonne', sa.Numeric(precision=18, scale=2), nullable=True, comment="Marge DML par tonne, convenue a l'avance"),
    sa.Column('taux_commission', sa.Numeric(precision=7, scale=4), nullable=True, comment='Uniquement si CONSIGNATION_POURCENTAGE'),
    sa.Column('plafond_avance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('nb_collectes', sa.Integer(), nullable=False),
    sa.Column('tonnage_cumule', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('ecart_poids_cumule_kg', sa.Numeric(precision=18, scale=3), nullable=False, comment='Cumul des ecarts poids paye / poids recu : negatif = perte pour DML'),
    sa.Column('humidite_moyenne_livree', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('nb_litiges', sa.Integer(), nullable=False),
    sa.Column('date_derniere_collecte', sa.Date(), nullable=True),
    sa.Column('is_actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint('taux_commission IS NULL OR (taux_commission >= 0 AND taux_commission <= 1)', name=op.f('ck_collecteurs_collecteur_taux_commission_valide')),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], name=op.f('fk_collecteurs_employe_id_employes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_principale_id'], ['zones_collecte.id'], name=op.f('fk_collecteurs_zone_principale_id_zones_collecte'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collecteurs')),
    sa.UniqueConstraint('employe_id', name=op.f('uq_collecteurs_employe_id'))
    )
    op.create_index(op.f('ix_collecteurs_code'), 'collecteurs', ['code'], unique=True)
    op.create_index(op.f('ix_collecteurs_created_at'), 'collecteurs', ['created_at'], unique=False)
    op.create_index(op.f('ix_collecteurs_date_derniere_collecte'), 'collecteurs', ['date_derniere_collecte'], unique=False)
    op.create_index(op.f('ix_collecteurs_is_actif'), 'collecteurs', ['is_actif'], unique=False)
    op.create_index(op.f('ix_collecteurs_is_deleted'), 'collecteurs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_collecteurs_nom'), 'collecteurs', ['nom'], unique=False)
    op.create_index(op.f('ix_collecteurs_statut'), 'collecteurs', ['statut'], unique=False)
    op.create_index(op.f('ix_collecteurs_telephone'), 'collecteurs', ['telephone'], unique=False)
    op.create_index(op.f('ix_collecteurs_zone_principale_id'), 'collecteurs', ['zone_principale_id'], unique=False)
    op.create_table('contrats_consignation',
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('collecteur_id', sa.Uuid(), nullable=False),
    sa.Column('mode_detention', sa.Enum('PROPRIETE', 'CONSIGNATION_POURCENTAGE', 'MARGE_FIXE_TONNE', name='modedetention', native_enum=False, length=50), nullable=False),
    sa.Column('marge_fixe_tonne', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('taux_commission', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('devise', sa.Enum('XAF', 'EUR', 'USD', 'NGN', 'XOF', name='devise', native_enum=False, length=50), nullable=False),
    sa.Column('date_signature', sa.Date(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('risque_perte_supporte_par_dml', sa.Boolean(), nullable=False, comment="True => achat-vente en substance, quel que soit l'intitule"),
    sa.Column('delai_reversement_jours', sa.Integer(), nullable=True),
    sa.Column('document_signe', sa.Boolean(), nullable=False),
    sa.Column('url_document', sa.Text(), nullable=True),
    sa.Column('clauses_particulieres', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint("mode_detention <> 'CONSIGNATION_POURCENTAGE' OR taux_commission IS NOT NULL", name=op.f('ck_contrats_consignation_contrat_commission_exige_taux')),
    sa.CheckConstraint("mode_detention <> 'MARGE_FIXE_TONNE' OR marge_fixe_tonne IS NOT NULL", name=op.f('ck_contrats_consignation_contrat_marge_fixe_exige_montant')),
    sa.ForeignKeyConstraint(['collecteur_id'], ['collecteurs.id'], name=op.f('fk_contrats_consignation_collecteur_id_collecteurs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], name=op.f('fk_contrats_consignation_created_by_id_utilisateurs'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['utilisateurs.id'], name=op.f('fk_contrats_consignation_updated_by_id_utilisateurs'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contrats_consignation'))
    )
    op.create_index(op.f('ix_contrats_consignation_collecteur_id'), 'contrats_consignation', ['collecteur_id'], unique=False)
    op.create_index(op.f('ix_contrats_consignation_created_at'), 'contrats_consignation', ['created_at'], unique=False)
    op.create_index(op.f('ix_contrats_consignation_created_by_id'), 'contrats_consignation', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_contrats_consignation_is_deleted'), 'contrats_consignation', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_contrats_consignation_numero'), 'contrats_consignation', ['numero'], unique=True)
    op.create_table('avances_collecteur',
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('collecteur_id', sa.Uuid(), nullable=False),
    sa.Column('statut', sa.Enum('ACCORDEE', 'PARTIELLEMENT_JUSTIFIEE', 'JUSTIFIEE', 'SOLDE_A_RENDRE', 'APUREE', 'LITIGIEUSE', name='statutavancecollecteur', native_enum=False, length=50), nullable=False),
    sa.Column('date_remise', sa.Date(), nullable=False),
    sa.Column('montant_remis', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('devise', sa.Enum('XAF', 'EUR', 'USD', 'NGN', 'XOF', name='devise', native_enum=False, length=50), nullable=False),
    sa.Column('mode_remise', sa.Enum('ESPECES', 'VIREMENT', 'CHEQUE', 'MOBILE_MONEY', 'TRAITE', 'COMPENSATION', 'CREDIT_DOCUMENTAIRE', name='modereglement', native_enum=False, length=50), nullable=False),
    sa.Column('compte_tresorerie_id', sa.Uuid(), nullable=True),
    sa.Column('mouvement_tresorerie_id', sa.Uuid(), nullable=True),
    sa.Column('remis_par_id', sa.Uuid(), nullable=True),
    sa.Column('montant_justifie', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_rendu', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_reste_du', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('date_apurement', sa.Date(), nullable=True),
    sa.Column('zone_prevue_id', sa.Uuid(), nullable=True),
    sa.Column('objet', sa.String(length=255), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint('montant_justifie >= 0 AND montant_rendu >= 0', name=op.f('ck_avances_collecteur_avance_apurement_positif')),
    sa.CheckConstraint('montant_remis > 0', name=op.f('ck_avances_collecteur_avance_montant_positif')),
    sa.ForeignKeyConstraint(['collecteur_id'], ['collecteurs.id'], name=op.f('fk_avances_collecteur_collecteur_id_collecteurs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['compte_tresorerie_id'], ['comptes_tresorerie.id'], name=op.f('fk_avances_collecteur_compte_tresorerie_id_comptes_tresorerie'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], name=op.f('fk_avances_collecteur_created_by_id_utilisateurs'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['mouvement_tresorerie_id'], ['mouvements_tresorerie.id'], name=op.f('fk_avances_collecteur_mouvement_tresorerie_id_mouvements_tresorerie'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['remis_par_id'], ['utilisateurs.id'], name=op.f('fk_avances_collecteur_remis_par_id_utilisateurs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['utilisateurs.id'], name=op.f('fk_avances_collecteur_updated_by_id_utilisateurs'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['zone_prevue_id'], ['zones_collecte.id'], name=op.f('fk_avances_collecteur_zone_prevue_id_zones_collecte'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avances_collecteur'))
    )
    op.create_index(op.f('ix_avances_collecteur_collecteur_id'), 'avances_collecteur', ['collecteur_id'], unique=False)
    op.create_index(op.f('ix_avances_collecteur_compte_tresorerie_id'), 'avances_collecteur', ['compte_tresorerie_id'], unique=False)
    op.create_index(op.f('ix_avances_collecteur_created_at'), 'avances_collecteur', ['created_at'], unique=False)
    op.create_index(op.f('ix_avances_collecteur_created_by_id'), 'avances_collecteur', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_avances_collecteur_date_remise'), 'avances_collecteur', ['date_remise'], unique=False)
    op.create_index(op.f('ix_avances_collecteur_is_deleted'), 'avances_collecteur', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_avances_collecteur_montant_reste_du'), 'avances_collecteur', ['montant_reste_du'], unique=False)
    op.create_index(op.f('ix_avances_collecteur_numero'), 'avances_collecteur', ['numero'], unique=True)
    op.create_index(op.f('ix_avances_collecteur_statut'), 'avances_collecteur', ['statut'], unique=False)
    op.create_index('ix_avances_collecteur_statut_date', 'avances_collecteur', ['statut', 'date_remise'], unique=False)
    op.create_table('collectes',
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('collecteur_id', sa.Uuid(), nullable=False),
    sa.Column('zone_id', sa.Uuid(), nullable=False),
    sa.Column('avance_id', sa.Uuid(), nullable=True),
    sa.Column('contrat_id', sa.Uuid(), nullable=True),
    sa.Column('statut', sa.Enum('EN_COURS', 'CLOTUREE', 'EXPEDIEE', 'RECEPTIONNEE', 'ANNULEE', name='statutcollecte', native_enum=False, length=50), nullable=False),
    sa.Column('mode_detention', sa.Enum('PROPRIETE', 'CONSIGNATION_POURCENTAGE', 'MARGE_FIXE_TONNE', name='modedetention', native_enum=False, length=50), nullable=False),
    sa.Column('marge_fixe_tonne_appliquee', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('taux_commission_applique', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_cloture', sa.Date(), nullable=True),
    sa.Column('campagne_agricole', sa.String(length=20), nullable=True),
    sa.Column('nombre_sacs_total', sa.Integer(), nullable=False),
    sa.Column('poids_theorique_kg', sa.Numeric(precision=18, scale=3), nullable=False, comment='Nb sacs x poids nominal du sac : ce que DML croit avoir achete'),
    sa.Column('montant_achat_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('frais_annexes', sa.Numeric(precision=18, scale=2), nullable=False, comment='Manutention, taxes de marche, sacherie, gardiennage'),
    sa.Column('devise', sa.Enum('XAF', 'EUR', 'USD', 'NGN', 'XOF', name='devise', native_enum=False, length=50), nullable=False),
    sa.Column('magasin_destination_id', sa.Uuid(), nullable=True),
    sa.Column('voyage_id', sa.Uuid(), nullable=True),
    sa.Column('nombre_sacs_expedies', sa.Integer(), nullable=True),
    sa.Column('nombre_sacs_recus', sa.Integer(), nullable=True),
    sa.Column('poids_reel_kg', sa.Numeric(precision=18, scale=3), nullable=True, comment="Pese a l'arrivee au magasin"),
    sa.Column('ecart_poids_kg', sa.Numeric(precision=18, scale=3), nullable=True, comment='poids_reel - poids_theorique. Negatif = DML a paye du vide.'),
    sa.Column('ecart_sacs', sa.Integer(), nullable=True),
    sa.Column('taux_humidite_magasin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('taux_impuretes_magasin', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('date_reception_magasin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint("mode_detention <> 'MARGE_FIXE_TONNE' OR marge_fixe_tonne_appliquee IS NOT NULL", name=op.f('ck_collectes_collecte_marge_fixe_exige_montant')),
    sa.CheckConstraint('nombre_sacs_total >= 0', name=op.f('ck_collectes_collecte_sacs_positifs')),
    sa.ForeignKeyConstraint(['avance_id'], ['avances_collecteur.id'], name=op.f('fk_collectes_avance_id_avances_collecteur'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collecteur_id'], ['collecteurs.id'], name=op.f('fk_collectes_collecteur_id_collecteurs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contrat_id'], ['contrats_consignation.id'], name=op.f('fk_collectes_contrat_id_contrats_consignation'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], name=op.f('fk_collectes_created_by_id_utilisateurs'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['magasin_destination_id'], ['magasins.id'], name=op.f('fk_collectes_magasin_destination_id_magasins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['utilisateurs.id'], name=op.f('fk_collectes_updated_by_id_utilisateurs'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['voyage_id'], ['voyages.id'], name=op.f('fk_collectes_voyage_id_voyages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones_collecte.id'], name=op.f('fk_collectes_zone_id_zones_collecte'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collectes'))
    )
    op.create_index(op.f('ix_collectes_avance_id'), 'collectes', ['avance_id'], unique=False)
    op.create_index(op.f('ix_collectes_campagne_agricole'), 'collectes', ['campagne_agricole'], unique=False)
    op.create_index(op.f('ix_collectes_collecteur_id'), 'collectes', ['collecteur_id'], unique=False)
    op.create_index('ix_collectes_collecteur_statut', 'collectes', ['collecteur_id', 'statut'], unique=False)
    op.create_index(op.f('ix_collectes_created_at'), 'collectes', ['created_at'], unique=False)
    op.create_index(op.f('ix_collectes_created_by_id'), 'collectes', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_collectes_date_debut'), 'collectes', ['date_debut'], unique=False)
    op.create_index(op.f('ix_collectes_ecart_poids_kg'), 'collectes', ['ecart_poids_kg'], unique=False)
    op.create_index(op.f('ix_collectes_is_deleted'), 'collectes', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_collectes_magasin_destination_id'), 'collectes', ['magasin_destination_id'], unique=False)
    op.create_index(op.f('ix_collectes_mode_detention'), 'collectes', ['mode_detention'], unique=False)
    op.create_index(op.f('ix_collectes_numero'), 'collectes', ['numero'], unique=True)
    op.create_index(op.f('ix_collectes_statut'), 'collectes', ['statut'], unique=False)
    op.create_index(op.f('ix_collectes_voyage_id'), 'collectes', ['voyage_id'], unique=False)
    op.create_index('ix_collectes_zone_date', 'collectes', ['zone_id', 'date_debut'], unique=False)
    op.create_index(op.f('ix_collectes_zone_id'), 'collectes', ['zone_id'], unique=False)
    op.create_table('lignes_collecte',
    sa.Column('collecte_id', sa.Uuid(), nullable=False),
    sa.Column('numero_ligne', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Uuid(), nullable=False),
    sa.Column('date_achat', sa.Date(), nullable=False),
    sa.Column('nom_vendeur', sa.String(length=180), nullable=True, comment='Producteur ou grossiste du marche'),
    sa.Column('telephone_vendeur', sa.String(length=40), nullable=True),
    sa.Column('base_achat', sa.Enum('AU_SAC', 'AU_KG', 'AU_TAS', name='baseachatmarche', native_enum=False, length=50), nullable=False),
    sa.Column('nombre_sacs', sa.Integer(), nullable=True),
    sa.Column('poids_nominal_sac_kg', sa.Numeric(precision=18, scale=3), nullable=True, comment="Poids suppose d'un sac (100 kg, 50 kg...)"),
    sa.Column('quantite_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('prix_unitaire', sa.Numeric(precision=18, scale=2), nullable=False, comment='Prix par sac ou par kg selon base_achat'),
    sa.Column('montant', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('devise', sa.Enum('XAF', 'EUR', 'USD', 'NGN', 'XOF', name='devise', native_enum=False, length=50), nullable=False),
    sa.Column('appreciation_qualite', sa.Enum('SEC', 'MOYEN', 'HUMIDE', 'NON_APPRECIE', name='appreciationqualitemarche', native_enum=False, length=50), nullable=False),
    sa.Column('taux_humidite_marche', sa.Numeric(precision=5, scale=2), nullable=True, comment='Renseigne uniquement si un humidimetre est disponible'),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("base_achat <> 'AU_SAC' OR nombre_sacs IS NOT NULL", name=op.f('ck_lignes_collecte_ligne_collecte_au_sac_exige_nombre')),
    sa.CheckConstraint('montant >= 0', name=op.f('ck_lignes_collecte_ligne_collecte_montant_positif')),
    sa.ForeignKeyConstraint(['collecte_id'], ['collectes.id'], name=op.f('fk_lignes_collecte_collecte_id_collectes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], name=op.f('fk_lignes_collecte_produit_id_produits'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lignes_collecte')),
    sa.UniqueConstraint('collecte_id', 'numero_ligne', name='uq_ligne_collecte_numero')
    )
    op.create_index(op.f('ix_lignes_collecte_collecte_id'), 'lignes_collecte', ['collecte_id'], unique=False)
    op.create_index(op.f('ix_lignes_collecte_created_at'), 'lignes_collecte', ['created_at'], unique=False)
    op.create_index(op.f('ix_lignes_collecte_produit_id'), 'lignes_collecte', ['produit_id'], unique=False)
    op.create_table('reversements_collecteur',
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('collecteur_id', sa.Uuid(), nullable=False),
    sa.Column('collecte_id', sa.Uuid(), nullable=True),
    sa.Column('statut', sa.Enum('A_PAYER', 'PARTIEL', 'PAYE', 'COMPENSE_AVANCE', 'BLOQUE_LITIGE', name='statutreversement', native_enum=False, length=50), nullable=False),
    sa.Column('mode_detention', sa.Enum('PROPRIETE', 'CONSIGNATION_POURCENTAGE', 'MARGE_FIXE_TONNE', name='modedetention', native_enum=False, length=50), nullable=False),
    sa.Column('tonnage_vendu', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('montant_vente_brut', sa.Numeric(precision=18, scale=2), nullable=False, comment="Encaisse aupres de l'industriel"),
    sa.Column('part_dml', sa.Numeric(precision=18, scale=2), nullable=False, comment='Marge fixe x tonnage, ou % du montant'),
    sa.Column('frais_deduits', sa.Numeric(precision=18, scale=2), nullable=False, comment='Transport, manutention, stockage refactures au collecteur'),
    sa.Column('avance_compensee', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_net_du', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('montant_paye', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('devise', sa.Enum('XAF', 'EUR', 'USD', 'NGN', 'XOF', name='devise', native_enum=False, length=50), nullable=False),
    sa.Column('date_calcul', sa.Date(), nullable=False),
    sa.Column('date_echeance', sa.Date(), nullable=True),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('mode_paiement', sa.Enum('ESPECES', 'VIREMENT', 'CHEQUE', 'MOBILE_MONEY', 'TRAITE', 'COMPENSATION', 'CREDIT_DOCUMENTAIRE', name='modereglement', native_enum=False, length=50), nullable=True),
    sa.Column('reference_paiement', sa.String(length=120), nullable=True),
    sa.Column('compte_tresorerie_id', sa.Uuid(), nullable=True),
    sa.Column('ecriture_id', sa.Uuid(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint('montant_paye >= 0', name=op.f('ck_reversements_collecteur_reversement_paye_positif')),
    sa.CheckConstraint('tonnage_vendu > 0', name=op.f('ck_reversements_collecteur_reversement_tonnage_positif')),
    sa.ForeignKeyConstraint(['collecte_id'], ['collectes.id'], name=op.f('fk_reversements_collecteur_collecte_id_collectes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collecteur_id'], ['collecteurs.id'], name=op.f('fk_reversements_collecteur_collecteur_id_collecteurs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['compte_tresorerie_id'], ['comptes_tresorerie.id'], name=op.f('fk_reversements_collecteur_compte_tresorerie_id_comptes_tresorerie'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], name=op.f('fk_reversements_collecteur_created_by_id_utilisateurs'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['ecriture_id'], ['ecritures_comptables.id'], name=op.f('fk_reversements_collecteur_ecriture_id_ecritures_comptables'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['utilisateurs.id'], name=op.f('fk_reversements_collecteur_updated_by_id_utilisateurs'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reversements_collecteur'))
    )
    op.create_index(op.f('ix_reversements_collecteur_collecte_id'), 'reversements_collecteur', ['collecte_id'], unique=False)
    op.create_index(op.f('ix_reversements_collecteur_collecteur_id'), 'reversements_collecteur', ['collecteur_id'], unique=False)
    op.create_index(op.f('ix_reversements_collecteur_created_at'), 'reversements_collecteur', ['created_at'], unique=False)
    op.create_index(op.f('ix_reversements_collecteur_created_by_id'), 'reversements_collecteur', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_reversements_collecteur_date_echeance'), 'reversements_collecteur', ['date_echeance'], unique=False)
    op.create_index('ix_reversements_collecteur_id_statut', 'reversements_collecteur', ['collecteur_id', 'statut'], unique=False)
    op.create_index(op.f('ix_reversements_collecteur_is_deleted'), 'reversements_collecteur', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_reversements_collecteur_montant_net_du'), 'reversements_collecteur', ['montant_net_du'], unique=False)
    op.create_index(op.f('ix_reversements_collecteur_numero'), 'reversements_collecteur', ['numero'], unique=True)
    op.create_index(op.f('ix_reversements_collecteur_statut'), 'reversements_collecteur', ['statut'], unique=False)
    op.create_foreign_key(op.f('fk_absences_created_by_id_utilisateurs'), 'absences', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_absences_updated_by_id_utilisateurs'), 'absences', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_attributions_fret_updated_by_id_utilisateurs'), 'attributions_fret', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_attributions_fret_created_by_id_utilisateurs'), 'attributions_fret', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_avances_salaire_created_by_id_utilisateurs'), 'avances_salaire', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_avances_salaire_updated_by_id_utilisateurs'), 'avances_salaire', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_bons_commande_client_created_by_id_utilisateurs'), 'bons_commande_client', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_bons_commande_client_updated_by_id_utilisateurs'), 'bons_commande_client', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_bons_livraison_created_by_id_utilisateurs'), 'bons_livraison', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_bons_livraison_updated_by_id_utilisateurs'), 'bons_livraison', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_bulletins_paie_created_by_id_utilisateurs'), 'bulletins_paie', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_bulletins_paie_updated_by_id_utilisateurs'), 'bulletins_paie', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_candidatures_fret_created_by_id_utilisateurs'), 'candidatures_fret', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_candidatures_fret_updated_by_id_utilisateurs'), 'candidatures_fret', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_chauffeur_vehicule_habituel', 'chauffeurs', 'vehicules', ['vehicule_habituel_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_commandes_achat_created_by_id_utilisateurs'), 'commandes_achat', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_commandes_achat_updated_by_id_utilisateurs'), 'commandes_achat', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_tresorerie_cca', 'comptes_tresorerie', 'comptes_courants_associes', ['compte_courant_associe_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_controles_qualite_updated_by_id_utilisateurs'), 'controles_qualite', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_controles_qualite_created_by_id_utilisateurs'), 'controles_qualite', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_declarations_fiscales_updated_by_id_utilisateurs'), 'declarations_fiscales', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_declarations_fiscales_created_by_id_utilisateurs'), 'declarations_fiscales', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_declarations_perte_created_by_id_utilisateurs'), 'declarations_perte', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_declarations_perte_updated_by_id_utilisateurs'), 'declarations_perte', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_departement_responsable', 'departements', 'employes', ['responsable_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_depenses_voyage_created_by_id_utilisateurs'), 'depenses_voyage', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_depenses_voyage_updated_by_id_utilisateurs'), 'depenses_voyage', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_ecritures_comptables_updated_by_id_utilisateurs'), 'ecritures_comptables', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_ecritures_comptables_created_by_id_utilisateurs'), 'ecritures_comptables', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_evaluations_chauffeur_created_by_id_utilisateurs'), 'evaluations_chauffeur', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_evaluations_chauffeur_updated_by_id_utilisateurs'), 'evaluations_chauffeur', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_factures_achat_created_by_id_utilisateurs'), 'factures_achat', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_factures_achat_updated_by_id_utilisateurs'), 'factures_achat', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_factures_vente_created_by_id_utilisateurs'), 'factures_vente', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_factures_vente_updated_by_id_utilisateurs'), 'factures_vente', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_incidents_voyage_created_by_id_utilisateurs'), 'incidents_voyage', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_incidents_voyage_updated_by_id_utilisateurs'), 'incidents_voyage', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_interactions_crm_created_by_id_utilisateurs'), 'interactions_crm', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_interactions_crm_updated_by_id_utilisateurs'), 'interactions_crm', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_inventaires_updated_by_id_utilisateurs'), 'inventaires', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_inventaires_created_by_id_utilisateurs'), 'inventaires', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_journal_tresorerie', 'journaux_comptables', 'comptes_tresorerie', ['compte_tresorerie_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_lettres_voiture_created_by_id_utilisateurs'), 'lettres_voiture', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_lettres_voiture_updated_by_id_utilisateurs'), 'lettres_voiture', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_litiges_transport_created_by_id_utilisateurs'), 'litiges_transport', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_litiges_transport_updated_by_id_utilisateurs'), 'litiges_transport', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_maintenances_created_by_id_utilisateurs'), 'maintenances', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_maintenances_updated_by_id_utilisateurs'), 'maintenances', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_missions_transport_created_by_id_utilisateurs'), 'missions_transport', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_missions_transport_updated_by_id_utilisateurs'), 'missions_transport', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_mouvements_compte_courant_updated_by_id_utilisateurs'), 'mouvements_compte_courant', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_mouvements_compte_courant_created_by_id_utilisateurs'), 'mouvements_compte_courant', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_mouvements_stock_created_by_id_utilisateurs'), 'mouvements_stock', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_mouvements_stock_updated_by_id_utilisateurs'), 'mouvements_stock', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_mouvements_tresorerie_created_by_id_utilisateurs'), 'mouvements_tresorerie', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_mouvements_tresorerie_updated_by_id_utilisateurs'), 'mouvements_tresorerie', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_offres_fret_created_by_id_utilisateurs'), 'offres_fret', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_offres_fret_updated_by_id_utilisateurs'), 'offres_fret', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_proformas_created_by_id_utilisateurs'), 'proformas', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_proformas_updated_by_id_utilisateurs'), 'proformas', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_ravitaillements_carburant_updated_by_id_utilisateurs'), 'ravitaillements_carburant', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_ravitaillements_carburant_created_by_id_utilisateurs'), 'ravitaillements_carburant', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_receptions_barriere_updated_by_id_utilisateurs'), 'receptions_barriere', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_receptions_barriere_created_by_id_utilisateurs'), 'receptions_barriere', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_reception_lot', 'receptions_barriere', 'lots', ['lot_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_reglements_client_updated_by_id_utilisateurs'), 'reglements_client', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_reglements_client_created_by_id_utilisateurs'), 'reglements_client', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_reglements_fournisseur_created_by_id_utilisateurs'), 'reglements_fournisseur', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_reglements_fournisseur_updated_by_id_utilisateurs'), 'reglements_fournisseur', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_relances_client_created_by_id_utilisateurs'), 'relances_client', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_relances_client_updated_by_id_utilisateurs'), 'relances_client', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_transferts_stock_created_by_id_utilisateurs'), 'transferts_stock', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_transferts_stock_updated_by_id_utilisateurs'), 'transferts_stock', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_transferts_tresorerie_updated_by_id_utilisateurs'), 'transferts_tresorerie', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_transferts_tresorerie_created_by_id_utilisateurs'), 'transferts_tresorerie', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_vehicule_remorque', 'vehicules', 'vehicules', ['remorque_attelee_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_voyages_created_by_id_utilisateurs'), 'voyages', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_voyages_updated_by_id_utilisateurs'), 'voyages', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_voyages_updated_by_id_utilisateurs'), 'voyages', type_='foreignkey')
    op.drop_constraint(op.f('fk_voyages_created_by_id_utilisateurs'), 'voyages', type_='foreignkey')
    op.drop_constraint('fk_vehicule_remorque', 'vehicules', type_='foreignkey')
    op.drop_constraint(op.f('fk_transferts_tresorerie_created_by_id_utilisateurs'), 'transferts_tresorerie', type_='foreignkey')
    op.drop_constraint(op.f('fk_transferts_tresorerie_updated_by_id_utilisateurs'), 'transferts_tresorerie', type_='foreignkey')
    op.drop_constraint(op.f('fk_transferts_stock_updated_by_id_utilisateurs'), 'transferts_stock', type_='foreignkey')
    op.drop_constraint(op.f('fk_transferts_stock_created_by_id_utilisateurs'), 'transferts_stock', type_='foreignkey')
    op.drop_constraint(op.f('fk_relances_client_updated_by_id_utilisateurs'), 'relances_client', type_='foreignkey')
    op.drop_constraint(op.f('fk_relances_client_created_by_id_utilisateurs'), 'relances_client', type_='foreignkey')
    op.drop_constraint(op.f('fk_reglements_fournisseur_updated_by_id_utilisateurs'), 'reglements_fournisseur', type_='foreignkey')
    op.drop_constraint(op.f('fk_reglements_fournisseur_created_by_id_utilisateurs'), 'reglements_fournisseur', type_='foreignkey')
    op.drop_constraint(op.f('fk_reglements_client_created_by_id_utilisateurs'), 'reglements_client', type_='foreignkey')
    op.drop_constraint(op.f('fk_reglements_client_updated_by_id_utilisateurs'), 'reglements_client', type_='foreignkey')
    op.drop_constraint('fk_reception_lot', 'receptions_barriere', type_='foreignkey')
    op.drop_constraint(op.f('fk_receptions_barriere_created_by_id_utilisateurs'), 'receptions_barriere', type_='foreignkey')
    op.drop_constraint(op.f('fk_receptions_barriere_updated_by_id_utilisateurs'), 'receptions_barriere', type_='foreignkey')
    op.drop_constraint(op.f('fk_ravitaillements_carburant_created_by_id_utilisateurs'), 'ravitaillements_carburant', type_='foreignkey')
    op.drop_constraint(op.f('fk_ravitaillements_carburant_updated_by_id_utilisateurs'), 'ravitaillements_carburant', type_='foreignkey')
    op.drop_constraint(op.f('fk_proformas_updated_by_id_utilisateurs'), 'proformas', type_='foreignkey')
    op.drop_constraint(op.f('fk_proformas_created_by_id_utilisateurs'), 'proformas', type_='foreignkey')
    op.drop_constraint(op.f('fk_offres_fret_updated_by_id_utilisateurs'), 'offres_fret', type_='foreignkey')
    op.drop_constraint(op.f('fk_offres_fret_created_by_id_utilisateurs'), 'offres_fret', type_='foreignkey')
    op.drop_constraint(op.f('fk_mouvements_tresorerie_updated_by_id_utilisateurs'), 'mouvements_tresorerie', type_='foreignkey')
    op.drop_constraint(op.f('fk_mouvements_tresorerie_created_by_id_utilisateurs'), 'mouvements_tresorerie', type_='foreignkey')
    op.drop_constraint(op.f('fk_mouvements_stock_updated_by_id_utilisateurs'), 'mouvements_stock', type_='foreignkey')
    op.drop_constraint(op.f('fk_mouvements_stock_created_by_id_utilisateurs'), 'mouvements_stock', type_='foreignkey')
    op.drop_constraint(op.f('fk_mouvements_compte_courant_created_by_id_utilisateurs'), 'mouvements_compte_courant', type_='foreignkey')
    op.drop_constraint(op.f('fk_mouvements_compte_courant_updated_by_id_utilisateurs'), 'mouvements_compte_courant', type_='foreignkey')
    op.drop_constraint(op.f('fk_missions_transport_updated_by_id_utilisateurs'), 'missions_transport', type_='foreignkey')
    op.drop_constraint(op.f('fk_missions_transport_created_by_id_utilisateurs'), 'missions_transport', type_='foreignkey')
    op.drop_constraint(op.f('fk_maintenances_updated_by_id_utilisateurs'), 'maintenances', type_='foreignkey')
    op.drop_constraint(op.f('fk_maintenances_created_by_id_utilisateurs'), 'maintenances', type_='foreignkey')
    op.drop_constraint(op.f('fk_litiges_transport_updated_by_id_utilisateurs'), 'litiges_transport', type_='foreignkey')
    op.drop_constraint(op.f('fk_litiges_transport_created_by_id_utilisateurs'), 'litiges_transport', type_='foreignkey')
    op.drop_constraint(op.f('fk_lettres_voiture_updated_by_id_utilisateurs'), 'lettres_voiture', type_='foreignkey')
    op.drop_constraint(op.f('fk_lettres_voiture_created_by_id_utilisateurs'), 'lettres_voiture', type_='foreignkey')
    op.drop_constraint('fk_journal_tresorerie', 'journaux_comptables', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventaires_created_by_id_utilisateurs'), 'inventaires', type_='foreignkey')
    op.drop_constraint(op.f('fk_inventaires_updated_by_id_utilisateurs'), 'inventaires', type_='foreignkey')
    op.drop_constraint(op.f('fk_interactions_crm_updated_by_id_utilisateurs'), 'interactions_crm', type_='foreignkey')
    op.drop_constraint(op.f('fk_interactions_crm_created_by_id_utilisateurs'), 'interactions_crm', type_='foreignkey')
    op.drop_constraint(op.f('fk_incidents_voyage_updated_by_id_utilisateurs'), 'incidents_voyage', type_='foreignkey')
    op.drop_constraint(op.f('fk_incidents_voyage_created_by_id_utilisateurs'), 'incidents_voyage', type_='foreignkey')
    op.drop_constraint(op.f('fk_factures_vente_updated_by_id_utilisateurs'), 'factures_vente', type_='foreignkey')
    op.drop_constraint(op.f('fk_factures_vente_created_by_id_utilisateurs'), 'factures_vente', type_='foreignkey')
    op.drop_constraint(op.f('fk_factures_achat_updated_by_id_utilisateurs'), 'factures_achat', type_='foreignkey')
    op.drop_constraint(op.f('fk_factures_achat_created_by_id_utilisateurs'), 'factures_achat', type_='foreignkey')
    op.drop_constraint(op.f('fk_evaluations_chauffeur_updated_by_id_utilisateurs'), 'evaluations_chauffeur', type_='foreignkey')
    op.drop_constraint(op.f('fk_evaluations_chauffeur_created_by_id_utilisateurs'), 'evaluations_chauffeur', type_='foreignkey')
    op.drop_constraint(op.f('fk_ecritures_comptables_created_by_id_utilisateurs'), 'ecritures_comptables', type_='foreignkey')
    op.drop_constraint(op.f('fk_ecritures_comptables_updated_by_id_utilisateurs'), 'ecritures_comptables', type_='foreignkey')
    op.drop_constraint(op.f('fk_depenses_voyage_updated_by_id_utilisateurs'), 'depenses_voyage', type_='foreignkey')
    op.drop_constraint(op.f('fk_depenses_voyage_created_by_id_utilisateurs'), 'depenses_voyage', type_='foreignkey')
    op.drop_constraint('fk_departement_responsable', 'departements', type_='foreignkey')
    op.drop_constraint(op.f('fk_declarations_perte_updated_by_id_utilisateurs'), 'declarations_perte', type_='foreignkey')
    op.drop_constraint(op.f('fk_declarations_perte_created_by_id_utilisateurs'), 'declarations_perte', type_='foreignkey')
    op.drop_constraint(op.f('fk_declarations_fiscales_created_by_id_utilisateurs'), 'declarations_fiscales', type_='foreignkey')
    op.drop_constraint(op.f('fk_declarations_fiscales_updated_by_id_utilisateurs'), 'declarations_fiscales', type_='foreignkey')
    op.drop_constraint(op.f('fk_controles_qualite_created_by_id_utilisateurs'), 'controles_qualite', type_='foreignkey')
    op.drop_constraint(op.f('fk_controles_qualite_updated_by_id_utilisateurs'), 'controles_qualite', type_='foreignkey')
    op.drop_constraint('fk_tresorerie_cca', 'comptes_tresorerie', type_='foreignkey')
    op.drop_constraint(op.f('fk_commandes_achat_updated_by_id_utilisateurs'), 'commandes_achat', type_='foreignkey')
    op.drop_constraint(op.f('fk_commandes_achat_created_by_id_utilisateurs'), 'commandes_achat', type_='foreignkey')
    op.drop_constraint('fk_chauffeur_vehicule_habituel', 'chauffeurs', type_='foreignkey')
    op.drop_constraint(op.f('fk_candidatures_fret_updated_by_id_utilisateurs'), 'candidatures_fret', type_='foreignkey')
    op.drop_constraint(op.f('fk_candidatures_fret_created_by_id_utilisateurs'), 'candidatures_fret', type_='foreignkey')
    op.drop_constraint(op.f('fk_bulletins_paie_updated_by_id_utilisateurs'), 'bulletins_paie', type_='foreignkey')
    op.drop_constraint(op.f('fk_bulletins_paie_created_by_id_utilisateurs'), 'bulletins_paie', type_='foreignkey')
    op.drop_constraint(op.f('fk_bons_livraison_updated_by_id_utilisateurs'), 'bons_livraison', type_='foreignkey')
    op.drop_constraint(op.f('fk_bons_livraison_created_by_id_utilisateurs'), 'bons_livraison', type_='foreignkey')
    op.drop_constraint(op.f('fk_bons_commande_client_updated_by_id_utilisateurs'), 'bons_commande_client', type_='foreignkey')
    op.drop_constraint(op.f('fk_bons_commande_client_created_by_id_utilisateurs'), 'bons_commande_client', type_='foreignkey')
    op.drop_constraint(op.f('fk_avances_salaire_updated_by_id_utilisateurs'), 'avances_salaire', type_='foreignkey')
    op.drop_constraint(op.f('fk_avances_salaire_created_by_id_utilisateurs'), 'avances_salaire', type_='foreignkey')
    op.drop_constraint(op.f('fk_attributions_fret_created_by_id_utilisateurs'), 'attributions_fret', type_='foreignkey')
    op.drop_constraint(op.f('fk_attributions_fret_updated_by_id_utilisateurs'), 'attributions_fret', type_='foreignkey')
    op.drop_constraint(op.f('fk_absences_updated_by_id_utilisateurs'), 'absences', type_='foreignkey')
    op.drop_constraint(op.f('fk_absences_created_by_id_utilisateurs'), 'absences', type_='foreignkey')
    op.drop_index(op.f('ix_reversements_collecteur_statut'), table_name='reversements_collecteur')
    op.drop_index(op.f('ix_reversements_collecteur_numero'), table_name='reversements_collecteur')
    op.drop_index(op.f('ix_reversements_collecteur_montant_net_du'), table_name='reversements_collecteur')
    op.drop_index(op.f('ix_reversements_collecteur_is_deleted'), table_name='reversements_collecteur')
    op.drop_index('ix_reversements_collecteur_id_statut', table_name='reversements_collecteur')
    op.drop_index(op.f('ix_reversements_collecteur_date_echeance'), table_name='reversements_collecteur')
    op.drop_index(op.f('ix_reversements_collecteur_created_by_id'), table_name='reversements_collecteur')
    op.drop_index(op.f('ix_reversements_collecteur_created_at'), table_name='reversements_collecteur')
    op.drop_index(op.f('ix_reversements_collecteur_collecteur_id'), table_name='reversements_collecteur')
    op.drop_index(op.f('ix_reversements_collecteur_collecte_id'), table_name='reversements_collecteur')
    op.drop_table('reversements_collecteur')
    op.drop_index(op.f('ix_lignes_collecte_produit_id'), table_name='lignes_collecte')
    op.drop_index(op.f('ix_lignes_collecte_created_at'), table_name='lignes_collecte')
    op.drop_index(op.f('ix_lignes_collecte_collecte_id'), table_name='lignes_collecte')
    op.drop_table('lignes_collecte')
    op.drop_index(op.f('ix_collectes_zone_id'), table_name='collectes')
    op.drop_index('ix_collectes_zone_date', table_name='collectes')
    op.drop_index(op.f('ix_collectes_voyage_id'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_statut'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_numero'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_mode_detention'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_magasin_destination_id'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_is_deleted'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_ecart_poids_kg'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_date_debut'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_created_by_id'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_created_at'), table_name='collectes')
    op.drop_index('ix_collectes_collecteur_statut', table_name='collectes')
    op.drop_index(op.f('ix_collectes_collecteur_id'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_campagne_agricole'), table_name='collectes')
    op.drop_index(op.f('ix_collectes_avance_id'), table_name='collectes')
    op.drop_table('collectes')
    op.drop_index('ix_avances_collecteur_statut_date', table_name='avances_collecteur')
    op.drop_index(op.f('ix_avances_collecteur_statut'), table_name='avances_collecteur')
    op.drop_index(op.f('ix_avances_collecteur_numero'), table_name='avances_collecteur')
    op.drop_index(op.f('ix_avances_collecteur_montant_reste_du'), table_name='avances_collecteur')
    op.drop_index(op.f('ix_avances_collecteur_is_deleted'), table_name='avances_collecteur')
    op.drop_index(op.f('ix_avances_collecteur_date_remise'), table_name='avances_collecteur')
    op.drop_index(op.f('ix_avances_collecteur_created_by_id'), table_name='avances_collecteur')
    op.drop_index(op.f('ix_avances_collecteur_created_at'), table_name='avances_collecteur')
    op.drop_index(op.f('ix_avances_collecteur_compte_tresorerie_id'), table_name='avances_collecteur')
    op.drop_index(op.f('ix_avances_collecteur_collecteur_id'), table_name='avances_collecteur')
    op.drop_table('avances_collecteur')
    op.drop_index(op.f('ix_contrats_consignation_numero'), table_name='contrats_consignation')
    op.drop_index(op.f('ix_contrats_consignation_is_deleted'), table_name='contrats_consignation')
    op.drop_index(op.f('ix_contrats_consignation_created_by_id'), table_name='contrats_consignation')
    op.drop_index(op.f('ix_contrats_consignation_created_at'), table_name='contrats_consignation')
    op.drop_index(op.f('ix_contrats_consignation_collecteur_id'), table_name='contrats_consignation')
    op.drop_table('contrats_consignation')
    op.drop_index(op.f('ix_collecteurs_zone_principale_id'), table_name='collecteurs')
    op.drop_index(op.f('ix_collecteurs_telephone'), table_name='collecteurs')
    op.drop_index(op.f('ix_collecteurs_statut'), table_name='collecteurs')
    op.drop_index(op.f('ix_collecteurs_nom'), table_name='collecteurs')
    op.drop_index(op.f('ix_collecteurs_is_deleted'), table_name='collecteurs')
    op.drop_index(op.f('ix_collecteurs_is_actif'), table_name='collecteurs')
    op.drop_index(op.f('ix_collecteurs_date_derniere_collecte'), table_name='collecteurs')
    op.drop_index(op.f('ix_collecteurs_created_at'), table_name='collecteurs')
    op.drop_index(op.f('ix_collecteurs_code'), table_name='collecteurs')
    op.drop_table('collecteurs')
    op.drop_index(op.f('ix_zones_collecte_village'), table_name='zones_collecte')
    op.drop_index(op.f('ix_zones_collecte_region'), table_name='zones_collecte')
    op.drop_index(op.f('ix_zones_collecte_is_deleted'), table_name='zones_collecte')
    op.drop_index(op.f('ix_zones_collecte_is_actif'), table_name='zones_collecte')
    op.drop_index(op.f('ix_zones_collecte_departement'), table_name='zones_collecte')
    op.drop_index(op.f('ix_zones_collecte_created_at'), table_name='zones_collecte')
    op.drop_index(op.f('ix_zones_collecte_code'), table_name='zones_collecte')
    op.drop_table('zones_collecte')
    # ### end Alembic commands ###
