"""utilisateur: blocage apres tentatives

Revision ID: e0dbf28e627c
Revises: 7b76bd3482cf
Create Date: 2026-08-29 16:23:00.579904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0dbf28e627c'
down_revision: Union[str, Sequence[str], None] = '7b76bd3482cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('bloque_jusqua', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateurs', 'bloque_jusqua')
    # ### end Alembic commands ###
