"""proforma: revision et version

Revision ID: fab2518185a2
Revises: 1b64ea87c61a
Create Date: 2026-08-30 22:31:08.858252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab2518185a2'
down_revision: Union[str, Sequence[str], None] = '1b64ea87c61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proformas', sa.Column('proforma_origine_id', sa.Uuid(), nullable=True, comment='Proforma revisee : garde la trace de la negociation'))
    op.add_column('proformas', sa.Column('version', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_proformas_proforma_origine_id'), 'proformas', ['proforma_origine_id'], unique=False)
    op.create_foreign_key(op.f('fk_proformas_proforma_origine_id_proformas'), 'proformas', 'proformas', ['proforma_origine_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_proformas_proforma_origine_id_proformas'), 'proformas', type_='foreignkey')
    op.drop_index(op.f('ix_proformas_proforma_origine_id'), table_name='proformas')
    op.drop_column('proformas', 'version')
    op.drop_column('proformas', 'proforma_origine_id')
    # ### end Alembic commands ###
