"""module traitement prestataire

Revision ID: ff50aad53044
Revises: ffd865944665
Create Date: 2026-08-28 08:21:51.304093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff50aad53044'
down_revision: Union[str, Sequence[str], None] = 'ffd865944665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prestataires',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=180), nullable=False),
    sa.Column('telephone', sa.String(length=40), nullable=True),
    sa.Column('adresse', sa.String(length=255), nullable=True),
    sa.Column('ville', sa.String(length=80), nullable=False),
    sa.Column('contact_principal', sa.String(length=150), nullable=True),
    sa.Column('magasin_id', sa.Uuid(), nullable=True),
    sa.Column('types_traitement', sa.String(length=255), nullable=True, comment='Prestations proposees, en clair'),
    sa.Column('prix_tonne', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('base_facturation', sa.Enum('TONNE_ENTREE', 'TONNE_SORTIE', 'FORFAIT_LOT', name='basefacturationtraitement', native_enum=False, length=50), nullable=False, comment="Tonne entree par defaut : son travail porte sur ce qu'il recoit"),
    sa.Column('devise', sa.Enum('XAF', 'EUR', 'USD', 'NGN', 'XOF', name='devise', native_enum=False, length=50), nullable=False),
    sa.Column('delai_habituel_jours', sa.Integer(), nullable=True),
    sa.Column('capacite_tonnes_jour', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('nb_traitements', sa.Integer(), nullable=False),
    sa.Column('tonnage_cumule', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('perte_inexpliquee_cumulee_kg', sa.Numeric(precision=18, scale=3), nullable=False, comment='Cumul des ecarts entre perte reelle et perte theorique de sechage'),
    sa.Column('nb_litiges', sa.Integer(), nullable=False),
    sa.Column('assurance_marchandise', sa.Boolean(), nullable=False, comment="Le prestataire couvre-t-il la marchandise qu'il detient ?"),
    sa.Column('contrat_signe', sa.Boolean(), nullable=False),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('is_actif', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['magasin_id'], ['magasins.id'], name=op.f('fk_prestataires_magasin_id_magasins'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prestataires'))
    )
    op.create_index(op.f('ix_prestataires_code'), 'prestataires', ['code'], unique=True)
    op.create_index(op.f('ix_prestataires_created_at'), 'prestataires', ['created_at'], unique=False)
    op.create_index(op.f('ix_prestataires_is_actif'), 'prestataires', ['is_actif'], unique=False)
    op.create_index(op.f('ix_prestataires_is_deleted'), 'prestataires', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_prestataires_magasin_id'), 'prestataires', ['magasin_id'], unique=True)
    op.create_index(op.f('ix_prestataires_nom'), 'prestataires', ['nom'], unique=False)
    op.create_table('traitements',
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('prestataire_id', sa.Uuid(), nullable=False),
    sa.Column('lot_source_id', sa.Uuid(), nullable=False),
    sa.Column('lot_traite_id', sa.Uuid(), nullable=True, comment='Lot fils cree en sortie de traitement'),
    sa.Column('statut', sa.Enum('PLANIFIE', 'EXPEDIE', 'EN_COURS', 'TERMINE', 'LIVRE_CLIENT', 'ANNULE', 'LITIGE', name='statuttraitement', native_enum=False, length=50), nullable=False),
    sa.Column('type_traitement', sa.Enum('SECHAGE', 'TRIAGE', 'NETTOYAGE', 'FUMIGATION', 'CALIBRAGE', 'CONDITIONNEMENT', 'MIXTE', name='typetraitement', native_enum=False, length=50), nullable=False),
    sa.Column('mouvement_sortie_id', sa.Uuid(), nullable=True),
    sa.Column('mouvement_entree_id', sa.Uuid(), nullable=True),
    sa.Column('date_expedition', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_retour_prevue', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('poids_entree_kg', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('poids_sortie_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('perte_reelle_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('perte_theorique_kg', sa.Numeric(precision=18, scale=3), nullable=True, comment='Perte expliquee par la deshydratation seule'),
    sa.Column('perte_inexpliquee_kg', sa.Numeric(precision=18, scale=3), nullable=True, comment="perte_reelle - perte_theorique : ce que la physique n'explique pas"),
    sa.Column('humidite_entree', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidite_sortie', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('impuretes_entree', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('impuretes_sortie', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('prix_tonne_applique', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('base_facturation', sa.Enum('TONNE_ENTREE', 'TONNE_SORTIE', 'FORFAIT_LOT', name='basefacturationtraitement', native_enum=False, length=50), nullable=False),
    sa.Column('tonnage_facture', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('cout_traitement', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('frais_transport', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('devise', sa.Enum('XAF', 'EUR', 'USD', 'NGN', 'XOF', name='devise', native_enum=False, length=50), nullable=False),
    sa.Column('facture_recue', sa.Boolean(), nullable=False),
    sa.Column('reference_facture', sa.String(length=80), nullable=True),
    sa.Column('niveau_alerte', sa.Enum('INFO', 'ATTENTION', 'CRITIQUE', 'URGENCE', name='niveaualerte', native_enum=False, length=50), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_reason', sa.String(length=255), nullable=True),
    sa.CheckConstraint('poids_entree_kg > 0', name=op.f('ck_traitements_traitement_poids_entree_positif')),
    sa.CheckConstraint('poids_sortie_kg IS NULL OR poids_sortie_kg > 0', name=op.f('ck_traitements_traitement_poids_sortie_positif')),
    sa.ForeignKeyConstraint(['created_by_id'], ['utilisateurs.id'], name=op.f('fk_traitements_created_by_id_utilisateurs'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['lot_source_id'], ['lots.id'], name=op.f('fk_traitements_lot_source_id_lots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lot_traite_id'], ['lots.id'], name=op.f('fk_traitements_lot_traite_id_lots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mouvement_entree_id'], ['mouvements_stock.id'], name=op.f('fk_traitements_mouvement_entree_id_mouvements_stock'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mouvement_sortie_id'], ['mouvements_stock.id'], name=op.f('fk_traitements_mouvement_sortie_id_mouvements_stock'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prestataire_id'], ['prestataires.id'], name=op.f('fk_traitements_prestataire_id_prestataires'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['utilisateurs.id'], name=op.f('fk_traitements_updated_by_id_utilisateurs'), ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_traitements'))
    )
    op.create_index(op.f('ix_traitements_created_at'), 'traitements', ['created_at'], unique=False)
    op.create_index(op.f('ix_traitements_created_by_id'), 'traitements', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_traitements_date_expedition'), 'traitements', ['date_expedition'], unique=False)
    op.create_index(op.f('ix_traitements_is_deleted'), 'traitements', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_traitements_lot_source_id'), 'traitements', ['lot_source_id'], unique=False)
    op.create_index(op.f('ix_traitements_lot_traite_id'), 'traitements', ['lot_traite_id'], unique=False)
    op.create_index(op.f('ix_traitements_numero'), 'traitements', ['numero'], unique=True)
    op.create_index(op.f('ix_traitements_perte_inexpliquee_kg'), 'traitements', ['perte_inexpliquee_kg'], unique=False)
    op.create_index(op.f('ix_traitements_perte_reelle_kg'), 'traitements', ['perte_reelle_kg'], unique=False)
    op.create_index(op.f('ix_traitements_prestataire_id'), 'traitements', ['prestataire_id'], unique=False)
    op.create_index('ix_traitements_prestataire_statut', 'traitements', ['prestataire_id', 'statut'], unique=False)
    op.create_index(op.f('ix_traitements_statut'), 'traitements', ['statut'], unique=False)
    op.drop_index(op.f('ix_lots_collecte_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_collecteur_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_mode_detention'), table_name='lots')
    op.drop_constraint(op.f('fk_lots_collecte_id_collectes'), 'lots', type_='foreignkey')
    op.drop_constraint(op.f('fk_lots_collecteur_id_collecteurs'), 'lots', type_='foreignkey')
    op.drop_column('lots', 'collecte_id')
    op.drop_column('lots', 'collecteur_id')
    op.drop_column('lots', 'mode_detention')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('mode_detention', sa.VARCHAR(length=50), autoincrement=False, nullable=False, comment='Ce lot appartient-il a DML ou est-il detenu pour un tiers ?'))
    op.add_column('lots', sa.Column('collecteur_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('lots', sa.Column('collecte_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_lots_collecteur_id_collecteurs'), 'lots', 'collecteurs', ['collecteur_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_lots_collecte_id_collectes'), 'lots', 'collectes', ['collecte_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_lots_mode_detention'), 'lots', ['mode_detention'], unique=False)
    op.create_index(op.f('ix_lots_collecteur_id'), 'lots', ['collecteur_id'], unique=False)
    op.create_index(op.f('ix_lots_collecte_id'), 'lots', ['collecte_id'], unique=False)
    op.drop_index(op.f('ix_traitements_statut'), table_name='traitements')
    op.drop_index('ix_traitements_prestataire_statut', table_name='traitements')
    op.drop_index(op.f('ix_traitements_prestataire_id'), table_name='traitements')
    op.drop_index(op.f('ix_traitements_perte_reelle_kg'), table_name='traitements')
    op.drop_index(op.f('ix_traitements_perte_inexpliquee_kg'), table_name='traitements')
    op.drop_index(op.f('ix_traitements_numero'), table_name='traitements')
    op.drop_index(op.f('ix_traitements_lot_traite_id'), table_name='traitements')
    op.drop_index(op.f('ix_traitements_lot_source_id'), table_name='traitements')
    op.drop_index(op.f('ix_traitements_is_deleted'), table_name='traitements')
    op.drop_index(op.f('ix_traitements_date_expedition'), table_name='traitements')
    op.drop_index(op.f('ix_traitements_created_by_id'), table_name='traitements')
    op.drop_index(op.f('ix_traitements_created_at'), table_name='traitements')
    op.drop_table('traitements')
    op.drop_index(op.f('ix_prestataires_nom'), table_name='prestataires')
    op.drop_index(op.f('ix_prestataires_magasin_id'), table_name='prestataires')
    op.drop_index(op.f('ix_prestataires_is_deleted'), table_name='prestataires')
    op.drop_index(op.f('ix_prestataires_is_actif'), table_name='prestataires')
    op.drop_index(op.f('ix_prestataires_created_at'), table_name='prestataires')
    op.drop_index(op.f('ix_prestataires_code'), table_name='prestataires')
    op.drop_table('prestataires')
    # ### end Alembic commands ###
