"""lot: mode de detention et lien collecte

Revision ID: ffd865944665
Revises: d1e3b3a3492f
Create Date: 2026-08-27 05:04:13.937633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd865944665'
down_revision: Union[str, Sequence[str], None] = 'd1e3b3a3492f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_avances_collecteur_created_by_id_utilisateurs'), 'avances_collecteur', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_avances_collecteur_updated_by_id_utilisateurs'), 'avances_collecteur', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_collectes_created_by_id_utilisateurs'), 'collectes', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_collectes_updated_by_id_utilisateurs'), 'collectes', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_contrats_consignation_created_by_id_utilisateurs'), 'contrats_consignation', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_contrats_consignation_updated_by_id_utilisateurs'), 'contrats_consignation', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('lots', sa.Column('collecte_id', sa.Uuid(), nullable=True))
    op.add_column('lots', sa.Column('collecteur_id', sa.Uuid(), nullable=True))
    op.add_column('lots', sa.Column('mode_detention', sa.Enum('PROPRIETE', 'CONSIGNATION_POURCENTAGE', 'MARGE_FIXE_TONNE', name='modedetention', native_enum=False, length=50), nullable=False, comment='Ce lot appartient-il a DML ou est-il detenu pour un tiers ?'))
    op.create_index(op.f('ix_lots_collecte_id'), 'lots', ['collecte_id'], unique=False)
    op.create_index(op.f('ix_lots_collecteur_id'), 'lots', ['collecteur_id'], unique=False)
    op.create_index(op.f('ix_lots_mode_detention'), 'lots', ['mode_detention'], unique=False)
    op.create_foreign_key(op.f('fk_lots_collecteur_id_collecteurs'), 'lots', 'collecteurs', ['collecteur_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_lots_collecte_id_collectes'), 'lots', 'collectes', ['collecte_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_reversements_collecteur_updated_by_id_utilisateurs'), 'reversements_collecteur', 'utilisateurs', ['updated_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key(op.f('fk_reversements_collecteur_created_by_id_utilisateurs'), 'reversements_collecteur', 'utilisateurs', ['created_by_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reversements_collecteur_created_by_id_utilisateurs'), 'reversements_collecteur', type_='foreignkey')
    op.drop_constraint(op.f('fk_reversements_collecteur_updated_by_id_utilisateurs'), 'reversements_collecteur', type_='foreignkey')
    op.drop_constraint(op.f('fk_lots_collecte_id_collectes'), 'lots', type_='foreignkey')
    op.drop_constraint(op.f('fk_lots_collecteur_id_collecteurs'), 'lots', type_='foreignkey')
    op.drop_index(op.f('ix_lots_mode_detention'), table_name='lots')
    op.drop_index(op.f('ix_lots_collecteur_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_collecte_id'), table_name='lots')
    op.drop_column('lots', 'mode_detention')
    op.drop_column('lots', 'collecteur_id')
    op.drop_column('lots', 'collecte_id')
    op.drop_constraint(op.f('fk_contrats_consignation_updated_by_id_utilisateurs'), 'contrats_consignation', type_='foreignkey')
    op.drop_constraint(op.f('fk_contrats_consignation_created_by_id_utilisateurs'), 'contrats_consignation', type_='foreignkey')
    op.drop_constraint(op.f('fk_collectes_updated_by_id_utilisateurs'), 'collectes', type_='foreignkey')
    op.drop_constraint(op.f('fk_collectes_created_by_id_utilisateurs'), 'collectes', type_='foreignkey')
    op.drop_constraint(op.f('fk_avances_collecteur_updated_by_id_utilisateurs'), 'avances_collecteur', type_='foreignkey')
    op.drop_constraint(op.f('fk_avances_collecteur_created_by_id_utilisateurs'), 'avances_collecteur', type_='foreignkey')
    # ### end Alembic commands ###
